before_script:
  - pip install virtualenv
  - virtualenv -p "$(which python)" /tmp/test

stages:
  - test

.run_script: &run_script
  script:
    - apt-get update
    - apt-get install -y collectd iproute2

    - source /tmp/test/bin/activate

    - pip install .

    - python setup.py test --addopts="--backend openwrt --backend mock --message-bus mqtt"

test_python3:
  image: registry.nic.cz/turris/foris-ci/python3
  stage: test
  <<: *run_script
